# --- РОУТ №1: USERS (ОТКРЫТЫЙ - точка входа) ---
spring.cloud.gateway.routes[0].id=users-auth
spring.cloud.gateway.routes[0].uri=lb://USERS-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/login**, /registration**, /api/users/**

# --- РОУТ №2: TETRIS (СТАТИКА - ТОЛЬКО HTTP) ---
spring.cloud.gateway.routes[1].id=tetris-ui
spring.cloud.gateway.routes[1].uri=lb://RAGING-HORSE-TETRIS-4-1
spring.cloud.gateway.routes[1].predicates[0]=Path=/html/**, /static/**, /img/**, /sounds/**, /getPhoto**, /getSnapShot**, /getSnapShotBest**

# --- РОУТ №3: TETRIS (WEBSOCKET И ИГРА) ---
spring.cloud.gateway.routes[2].id=tetris-ws
spring.cloud.gateway.routes[2].uri=lb:ws://RAGING-HORSE-TETRIS-4-1
spring.cloud.gateway.routes[2].predicates[0]=Path=/game/**, /websocket/**, /sockjs/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# --- РОУТ №4: MONGO (ЗАЩИЩЕН) ---
spring.cloud.gateway.routes[3].id=mongo-service
spring.cloud.gateway.routes[3].uri=lb://MONGO-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/mongo-service/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[3].filters[1]=AuthenticationFilter

# --- РОУТ №5: GAME PG (ЗАЩИЩЕН) ---
spring.cloud.gateway.routes[4].id=pg-service
spring.cloud.gateway.routes[4].uri=lb://GAME-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/game-service/**
spring.cloud.gateway.routes[4].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[4].filters[1]=AuthenticationFilter

# Включаем поддержку виртуальных потоков для фоновых задач Spring Boot 3.4
spring.threads.virtual.enabled=true

jwt.secret=mySecretKeyForTetrisProjectWhichMustBeAtLeast32CharactersLong!
server.port=5555
spring.application.name=gateway-service

eureka.client.service-url.defaultZone=http://localhost:1111/eureka/

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOriginPatterns=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true