# Основные настройки приложения
spring.application.name=gateway-service
server.port=9000

# Регистрация в Eureka (указываем тот же адрес, что в основном сервисе)
eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka
eureka.instance.leaseRenewalIntervalInSeconds=5

--- НАСТРОЙКИ РОУТОВ ---


spring.cloud.gateway.routes[0].id=tetris-app
spring.cloud.gateway.routes[0].uri=lb://RAGING-HORSE-TETRIS-4-1
spring.cloud.gateway.routes[0].predicates[0]=Path=/login, /game/**, /static/**, /websocket/**, /register/**, /sockjs/**, /html/**, /img/**, /sounds/**, /getPhoto/**, /getSnapShot/**, /getSnapShotBest/**

# --- РОУТ №2: USERS ---
spring.cloud.gateway.routes[1].id=users-service
spring.cloud.gateway.routes[1].uri=lb://USERS-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users-service/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# --- РОУТ №3: MONGO ---
spring.cloud.gateway.routes[2].id=mongo-service
spring.cloud.gateway.routes[2].uri=lb://MONGO-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/mongo-service/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# --- РОУТ №4: GAME (PG) ---
spring.cloud.gateway.routes[3].id=pg-service
spring.cloud.gateway.routes[3].uri=lb://GAME-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/game-service/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1

# Настройки мониторинга (Actuator)
management.endpoints.web.exposure.include=gateway,health,info

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*

